### ISSUE TITLE
Page title shows URL not an actual title.

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#2955]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.55.26

### Expected behavior

Should show something like "Site name: News" when viewing the news module

### Actual behavior

shows "http://localhost/Conference/news"

### Steps to reproduce

I have yet to see any page title in 1.4.3 that actually shows a nice title.  In General Settings, Page title structure = %pagetitle%, and startmodule still set to staticpage.

**Comment by craigh** [comment]
`/search` has a nice title "Site Search"

I believe the issue here is that the legacy method of setting the page title is not working with the new theme engine. @robbrandt I'm goes you are only referring to legacy modules like News or Content?

Maybe we can look in to a way to make the title thing more BC, but this gets harder and harder as we near Core-2.0.

**Comment by robbrandt** [comment]
No sir.  It appears on every page I've looked at, at the time.  Home, using the default static page, any admin page, etc.  I am looking again now, and I am finding a few that work.  The User account panel works. Search works.

If the Admin Panel and Static front page are still legacy modules, then what you are saying would be true.  However that would be most of the interesting pages in a new Core installation and looks bad.

**Comment by Guite** [comment]
The fix I've commited was for legacy modules. Page titles work for new and old-style modules now.

Reopening nevertheless, until your issue is found.
Which theme are you using? Which admin panel pages don't work? Which other pages don't work?

**Comment by robbrandt** [comment]
I am using the Bootstrap theme.
I have yet to find an admin page that DOES shot a proper title.

For example, http://localhost/Conference/theme/admin/view.
Also, http://localhost/Conference/users/admin/list fails, although http://localhost/Conference/users/account is fine.
Similarly http://localhost/Conference/search/ works, but http://localhost/Conference/search/config/config doesn't.

**Comment by craigh** [comment]
> http://localhost/Conference/users/admin/list fails

fails what?

are you using an up-to-date pull of 1.4.3? (e.g. did you update after @Guite's fixes?)

**Comment by robbrandt** [comment]
Haven't updated since I posted this.  Axel said he fixed legacy modules, I would think users is not legacy?  But I'm not at all clear on what's legacy and what's not. Fails = does not show a proper page title.

**Comment by craigh** [comment]
please update

**Comment by craigh** [comment]
So you don't probably know it, but you are describing two separate problems.

1) Legacy modules (like News) showing in a Twig theme. @Guite has corrected this I think ✅ 
2) Core-2.0 modules with Twig templates (like `/users/admin/list`) where the value simply isn't set. 😄

**Comment by craigh** [comment]
so I just fixed **that** one. 😉

**Comment by Guite** [comment]
So what remains here is that we should add missing title settings, right?

> For example, http://localhost/Conference/theme/admin/view.
> ... works, but http://localhost/Conference/search/config/config doesn't.

**Comment by craigh** [comment]
> So what remains here is that we should add missing title settings, right?

I guess so.

**Comment by robbrandt** [comment]
OK, page titles for Content is showing up.  News still shows a URL in admin, but does show a proper title for users. The home page (still set to Static) shows a URL.  The admin panel still shows URLs in all overviews.

Using build 115 from ci.

**Comment by Guite** [comment]
Fixed in #2980

**Comment by robbrandt** [comment]
Looks good except for the default Home page (static frontpage)

**Comment by craigh** [comment]
What does it say now? What would you like it to say?

**Comment by robbrandt** [comment]
It currently says 
"http://localhost/zcs1/"

It should say something like "Welcome to Zikula".

**Comment by Guite** [comment]
Isn't the theme responsible for setting an appropriate title for the home page? If you do a business page you do not want _Welcome to Zikula_, do you?

**Comment by robbrandt** [comment]
True, but nor do you want "This site is powered by Zikula!" and all that follows.
I don't think the staticpage title showing a path is all that big a deal, although it will be the first impression made with someone installing it for the first time.
Honestly, I've never used staticpage in a production site, so I don't have any idea where it's title is set.  If it's in the theme, and it's the default theme, it's still a core issue even if it's a minor one.

**Comment by craigh** [comment]
here's a site with a static front page: http://zikula.org 😁

**Comment by craigh** [comment]
It should default to the sitename probably

**Comment by craigh** [comment]
I'll look into it

**Comment by craigh** [comment]
supposed to already be doing that here: https://github.com/zikula/core/blob/fa02e8c9be3753682b8871b44416cf8b1009659c/src/system/ThemeModule/EventListener/DefaultPageVarSetterListener.php#L62-L62

**Comment by craigh** [comment]
also here:
https://github.com/zikula/core/blob/919c079525b4a719fd17633240053085e42cc27f/src/themes/BootstrapTheme/Resources/views/Include/header.html.twig#L5-L5

**Comment by Guite** [comment]
> I'll look into it

Thank you! Maybe there is something wrong with the `DefaultPageVarSetterListener`... I don't know.

**Comment by Guite** [comment]
Created a follow-up issue #2998
